# Generated by Django 3.2.23 on 2024-01-18 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'shop',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('review', models.TextField(max_length=255)),
                ('stars', models.IntegerField(max_length=255)),
                ('shop_id', models.ForeignKey(db_column='shop_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='shop', to='backend.shop')),
            ],
            options={
                'db_table': 'review',
                'managed': True,
            },
        ),
    ]
